[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Explicitly add the Next.js runtime (often auto-detected, this makes it bulletproof)
[[plugins]]
  package = "@netlify/plugin-nextjs"
